spring.application.name=rafi-day-2

# Database Configuration
spring.datasource.url=jdbc:postgresql://eCentrix.local:5432/db10
spring.datasource.username=user10
spring.datasource.password=userpass10
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.pattern.console=%d{HH:mm:ss} [%thread{id}] [%p] %c{0} - %m%n

# Server
server.port=8080

# Scalar
springdoc.scalar.path=/scalar
scalar.enabled=true
scalar.url=/api-docs

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true