spring.application.name=calculator

# Log format in console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Log format in file
logging.file.name=log/application.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Log level configuration
logging.level.com.bootcamp=DEBUG
logging.level.root=INFO

# Logback rolling policy configuration
logging.logback.rollingpolicy.file-name-pattern=log/application-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=1MB
logging.logback.rollingpolicy.max-history=5